// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	data "github.com/floydjones1/fiber-app/internal/data"
	mock "github.com/stretchr/testify/mock"
)

// MockUserStore is an autogenerated mock type for the UserStorer type
type MockUserStore struct {
	mock.Mock
}

// GetUserByEmail provides a mock function with given fields: email
func (_m *MockUserStore) GetUserByEmail(email string) (*data.User, bool, error) {
	ret := _m.Called(email)

	var r0 *data.User
	if rf, ok := ret.Get(0).(func(string) *data.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.User)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// InsertUser provides a mock function with given fields: user
func (_m *MockUserStore) InsertUser(user *data.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*data.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
